### PR TITLE
Fixes #43

### LINKED ISSUE #43: Incorrectly tries to umarshal trigger responses as `BufferedEvents`
The Pusher docs state that requests to trigger events should return an empty JSON object. However we are umarshaling these into `BufferedEvents`, which presumably never has any effect.

### PR DESCRIPTION
**Pull request by pyjac**
return only err on trigger

#43

### CODE REVIEW

**Comment by WillSewell** [comment]
Thanks for this. I think you can also remove the `unmarshalledBufferedEvents` function and `BufferedEvents` type.

**Comment by pyjac** [comment]
@WillSewell Ok

**Comment by pyjac** [comment]
@WillSewell Done

**Comment by WillSewell** [comment]
This looks good to me. @kn100 I'll let you give it a once-over and merge + release. Thanks again @pyjac!

**Pull request merged**
