### PR TITLE
rename keys in our notification representation to match APNs/GCM key …

### PR DESCRIPTION
**Pull request by jameshfisher**
…names

### CODE REVIEW

**Comment by jameshfisher** [comment]
This is a breaking API change - the only user I know of is Thermidor; do we have others?

**Comment by jpatel531** [comment]
@jameshfisher - i thought you were gonna change things to map[string]interface{} s ?

**Comment by jameshfisher** [comment]
@jpatel531 ah yeah I was going to do that eventually - initially just made this smaller change

**Comment by kn100** [comment]
Closing due to age and also http://pusher.com/beams

**Pull request closed without merging**
